### ISSUE TITLE
Questions for Chris at Back to Earth

### ISSUE THREAD

**Issue by Dr-Nutter** [Dr-Nutter/Stansbatch#207]
Need to figure out exact quantities
Discussion around where we would want the heavier weight wet boards. (4 zones)
Delivery - can this be staged?

**Comment by Dr-Nutter** [comment]
Joist spacing
Rafter spacing
Plinth insulation?
Cut off the lower tongue / groove?

**Comment by Dr-Nutter** [comment]
Is the 220mm flex appropriate? Given the Joist sizes that we're specifying.

**Comment by DrLoebl** [comment]
Recommended render people? What should be the cost?

**Comment by Dr-Nutter** [comment]
What is the 2mm (2K?) render
What are the options for finish surface
Is it possible to access a colour swatch?

**Comment by Dr-Nutter** [comment]
planning out the courses? If you can't get the 300mm min distance between an edge and a window, is it better to cut a row of boards?

**Comment by Dr-Nutter** [comment]
What is the polystyrene plinth? do you supply? do we need it? what is the aluminium base rail thing
looking at the video, the polystyrene is coated in slurry but what would that then be glued on to in our case?

**Comment by Dr-Nutter** [comment]
Detail around outside corners. Do we need a supporting 100mm timber?

**Comment by Dr-Nutter** [comment]
Detail around inside corner. Do we need to tuck it in, behind next piece?

**Comment by Dr-Nutter** [comment]
Connection between roof and wall boards. How to achieve air tightness?

**Comment by Dr-Nutter** [comment]
If there are places that will be inaccessible from the inside we'll need to add the flex before putting the outer boarding on. Is this OK from a weathering point of view.

**Comment by Dr-Nutter** [comment]
How to mitigate and deal with cracking caused by oak movement?

**Comment by Dr-Nutter** [comment]
Presume we work from the outside in when adding the different layers of insulation

**Comment by Dr-Nutter** [comment]
Baumit swatches?

**Comment by Dr-Nutter** [comment]
Need to do any thing special when drilling through the render to prevent water ingress?

**Comment by Dr-Nutter** [comment]
What about window reveal board?
